apiVersion: v1
kind: Service
metadata:
  name: flask-inventory-service
spec:
  selector:
    app: flask-inventory-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
