version: "3"

services:
  flask-inventory-app:
    build: 
    ports:
      - "5100:5100"
    networks:
      - monitoring-net
      context: .
      dockerfile: Dockerfile

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
